spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 4542at7s

#  security:
#    user:
#      name: root
#      password: 123456
#      roles: ROLE_USER

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml