package com.stumblegit.core.model;

import com.stumblegit.core.model.root.UserRoot;
import java.io.Serializable;
import java.util.Date;

public class User extends UserRoot implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_expired
     *
     * @mbg.generated
     */
    private Byte accountExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.account_locked
     *
     * @mbg.generated
     */
    private Byte accountLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.authorities
     *
     * @mbg.generated
     */
    private String authorities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.credentials_expired
     *
     * @mbg.generated
     */
    private Byte credentialsExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.disabled
     *
     * @mbg.generated
     */
    private Byte disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_expired
     *
     * @return the value of users.account_expired
     *
     * @mbg.generated
     */
    public Byte getAccountExpired() {
        return accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_expired
     *
     * @param accountExpired the value for users.account_expired
     *
     * @mbg.generated
     */
    public void setAccountExpired(Byte accountExpired) {
        this.accountExpired = accountExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.account_locked
     *
     * @return the value of users.account_locked
     *
     * @mbg.generated
     */
    public Byte getAccountLocked() {
        return accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.account_locked
     *
     * @param accountLocked the value for users.account_locked
     *
     * @mbg.generated
     */
    public void setAccountLocked(Byte accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.authorities
     *
     * @return the value of users.authorities
     *
     * @mbg.generated
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.authorities
     *
     * @param authorities the value for users.authorities
     *
     * @mbg.generated
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities == null ? null : authorities.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.credentials_expired
     *
     * @return the value of users.credentials_expired
     *
     * @mbg.generated
     */
    public Byte getCredentialsExpired() {
        return credentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.credentials_expired
     *
     * @param credentialsExpired the value for users.credentials_expired
     *
     * @mbg.generated
     */
    public void setCredentialsExpired(Byte credentialsExpired) {
        this.credentialsExpired = credentialsExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.disabled
     *
     * @return the value of users.disabled
     *
     * @mbg.generated
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.disabled
     *
     * @param disabled the value for users.disabled
     *
     * @mbg.generated
     */
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_at
     *
     * @return the value of users.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_at
     *
     * @param createdAt the value for users.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_at
     *
     * @return the value of users.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_at
     *
     * @param updatedAt the value for users.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}